// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pezvdlaliydqrbblnhaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlenZkbGFsaXlkcXJiYmxuaGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODQ5OTEsImV4cCI6MjA2OTQ2MDk5MX0.IbeCdITRbaf7d-r3B2dT9VZcuWQp64awL-Zk5_GlKwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});